name: teste_tecnico_02
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  bonfire: ^2.7.1
  provider: ^6.0.3
  just_audio: ^0.9.28

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/sounds/
    - assets/images/
    - assets/images/maps/
    - assets/images/sprites/

  fonts:
    - family: Minecraft
      fonts:
        - asset: assets/fonts/Minecraft.ttf